export default (small, big, huge) => {
    return [
        {
            id: 101,
            styles: {
                right: big,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "start",
            name: "Старт",
        },
        {
            id: 102,
            styles: {
                right: big + small,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 103,
            styles: {
                right: big + small * 2,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 104,
            styles: {
                right: big + small * 3,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 105,
            styles: {
                right: big + small * 4,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 106,
            styles: {
                right: big + small * 5,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 107,
            styles: {
                right: big + small * 6,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 108,
            styles: {
                right: big + small * 7,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 109,
            styles: {
                right: big + small * 8,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 110,
            styles: {
                right: big + small * 9,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 111,
            styles: {
                right: big + small * 10,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 112,
            styles: {
                right: big + small * 11,
                bottom: 0,
                width: huge,
                height: big,
                rotate: '-rotate-45',
            },
            type: "bankruptcy",
            name: "Банкрутство",
        },
        {
            id: 113,
            styles: {
                right: big + huge + small * 11,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 114,
            styles: {
                right: big + huge + small * 12,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 115,
            styles: {
                right: big + huge + small * 13,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 116,
            styles: {
                right: big + huge + small * 14,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 117,
            styles: {
                right: big + huge + small * 15,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 118,
            styles: {
                right: big + huge + small * 16,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 119,
            styles: {
                right: big + huge + small * 17,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 120,
            styles: {
                right: big + huge + small * 18,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 121,
            styles: {
                right: big + huge + small * 19,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 122,
            styles: {
                right: big + huge + small * 20,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 123,
            styles: {
                right: big + huge + small * 21,
                bottom: 0,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 124,
            styles: {
                right: big + huge + small * 22,
                bottom: 0,
                width: big,
                height: big,
                rotate: '-rotate-45',
            },
            type: "profit",
            name: "Прибуток",
        },
// *************************************************
        {
            id: 125,
            styles: {
                bottom: big,
                left: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 126,
            styles: {
                bottom: big + small,
                left: 0,
                width: big,
                height: small,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 127,
            styles: {
                bottom: big + small * 2,
                left: 0,
                width: big,
                height: small,
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 128,
            styles: {
                bottom: big + small * 3,
                left: 0,
                width: big,
                height: small,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 129,
            styles: {
                bottom: big + small * 4,
                left: 0,
                width: big,
                height: small,
            },
            type: "wedding",
            name: "Весілля",
        },
        {
            id: 130,
            styles: {
                bottom: big + small * 5,
                left: 0,
                width: big,
                height: small,
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 131,
            styles: {
                bottom: big + small * 6,
                left: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 132,
            styles: {
                bottom: big + small * 7,
                left: 0,
                width: big,
                height: small,
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 133,
            styles: {
                bottom: big + small * 8,
                left: 0,
                width: big,
                height: small,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 134,
            styles: {
                bottom: big + small * 9,
                left: 0,
                width: big,
                height: small,
            },
            type: "vacation",
            name: "Відпустка",
        },
        {
            id: 135,
            styles: {
                bottom: big + small * 10,
                left: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 136,
            styles: {
                bottom: big + small * 11,
                left: 0,
                width: big,
                height: small,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 137,
            styles: {
                bottom: big + small * 12,
                left: 0,
                width: big,
                height: small,
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 138,
            styles: {
                bottom: big + small * 13,
                left: 0,
                width: big,
                height: small,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 139,
            styles: {
                bottom: big + small * 14,
                left: 0,
                width: big,
                height: big,
                rotate: '-rotate-45',
            },
            type: "profit",
            name: "Прибуток",
        },
// *************************************************
        {
            id: 140,
            styles: {
                top: 0,
                left: big,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 141,
            styles: {
                top: 0,
                left: big + small,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 142,
            styles: {
                top: 0,
                left: big + small * 2,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 143,
            styles: {
                top: 0,
                left: big + small * 3,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 144,
            styles: {
                top: 0,
                left: big + small * 4,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 145,
            styles: {
                top: 0,
                left: big + small * 5,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 146,
            styles: {
                top: 0,
                left: big + small * 6,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 147,
            styles: {
                top: 0,
                left: big + small * 7,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 148,
            styles: {
                top: 0,
                left: big + small * 8,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 149,
            styles: {
                top: 0,
                left: big + small * 9,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 150,
            styles: {
                top: 0,
                left: big + small * 10,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 151,
            styles: {
                top: 0,
                left: big + small * 11,
                width: huge,
                height: big,
                rotate: '-rotate-45',
            },
            type: "baby",
            name: "Народження дитини",
        },
        {
            id: 152,
            styles: {
                top: 0,
                left: big + huge + small * 11,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 153,
            styles: {
                top: 0,
                left: big + huge + small * 12,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 154,
            styles: {
                top: 0,
                left: big + huge + small * 13,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 155,
            styles: {
                top: 0,
                left: big + huge + small * 14,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 156,
            styles: {
                top: 0,
                left: big + huge + small * 15,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 157,
            styles: {
                top: 0,
                left: big + huge + small * 16,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 158,
            styles: {
                top: 0,
                left: big + huge + small * 17,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "divorce",
            name: "Розлучення",
        },
        {
            id: 159,
            styles: {
                top: 0,
                left: big + huge + small * 18,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 160,
            styles: {
                top: 0,
                left: big + huge + small * 19,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 161,
            styles: {
                top: 0,
                left: big + huge + small * 20,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 162,
            styles: {
                top: 0,
                left: big + huge + small * 21,
                width: small,
                height: big,
                rotate: '-rotate-90',
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 163,
            styles: {
                top: 0,
                left: big + huge + small * 22,
                width: big,
                height: big,
                rotate: '-rotate-45',
            },
            type: "profit",
            name: "Прибуток",
        },
// *************************************************
        {
            id: 164,
            styles: {
                top: big,
                right: 0,
                width: big,
                height: small,
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 165,
            styles: {
                top: big + small,
                right: 0,
                width: big,
                height: small,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 166,
            styles: {
                top: big + small * 2,
                right: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 167,
            styles: {
                top: big + small * 3,
                right: 0,
                width: big,
                height: small,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 168,
            styles: {
                top: big + small * 4,
                right: 0,
                width: big,
                height: small,
            },
            type: "firing",
            name: "Звільнення",
        },
        {
            id: 169,
            styles: {
                top: big + small * 5,
                right: 0,
                width: big,
                height: small,
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 170,
            styles: {
                top: big + small * 6,
                right: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 171,
            styles: {
                top: big + small * 7,
                right: 0,
                width: big,
                height: small,
            },
            type: "buys",
            name: "Покупки",
        },
        {
            id: 172,
            styles: {
                top: big + small * 8,
                right: 0,
                width: big,
                height: small,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 173,
            styles: {
                top: big + small * 9,
                right: 0,
                width: big,
                height: small,
            },
            type: "wedding",
            name: "Весілля",
        },
        {
            id: 174,
            styles: {
                top: big + small * 10,
                right: 0,
                width: big,
                height: small,
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 175,
            styles: {
                top: big + small * 11,
                right: 0,
                width: big,
                height: small,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 176,
            styles: {
                top: big + small * 12,
                right: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 177,
            styles: {
                top: big + small * 13,
                right: 0,
                width: big,
                height: small,
            },
            type: "expenses",
            name: "Витрати",
        },
        {
            id: 178,
            styles: {
                top: big + small * 14,
                right: 0,
                width: big,
                height: big,
                rotate: '-rotate-45',
            },
            type: "profit",
            name: "Прибуток",
        },
    ];
};
