export default (small, big) => {
    return [
        {
            id: 201,
            styles: {
                right: big,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "start",
            name: "Старт",
        },
        {
            id: 202,
            styles: {
                right: big + small,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 203,
            styles: {
                right: big + small * 2,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "buys",
            name: "Великі покупки",
        },
        {
            id: 204,
            styles: {
                right: big + small * 3,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 205,
            styles: {
                right: big + small * 4,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 206,
            styles: {
                right: big + small * 5,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 207,
            styles: {
                right: big + small * 6,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 208,
            styles: {
                right: big + small * 7,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 209,
            styles: {
                right: big + small * 8,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 210,
            styles: {
                right: big + small * 9,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 211,
            styles: {
                right: big + small * 10,
                bottom: 0,
                width: big,
                height: big,
            },
            type: "bankruptcy",
            name: "Банкрутство",
        },
        {
            id: 212,
            styles: {
                right: big * 2 + small * 10,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 213,
            styles: {
                right: big * 2 + small * 11,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 214,
            styles: {
                right: big * 2 + small * 12,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "buys",
            name: "Великі покупки",
        },
        {
            id: 215,
            styles: {
                right: big * 2 + small * 13,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 216,
            styles: {
                right: big * 2 + small * 14,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 217,
            styles: {
                right: big * 2 + small * 15,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 218,
            styles: {
                right: big * 2 + small * 16,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 219,
            styles: {
                right: big * 2 + small * 17,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 220,
            styles: {
                right: big * 2 + small * 18,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "buys",
            name: "Великі покупки",
        },
        {
            id: 221,
            styles: {
                right: big * 2 + small * 19,
                bottom: 0,
                width: small,
                height: big,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 222,
            styles: {
                right: big * 2 + small * 20,
                bottom: 0,
                width: big,
                height: big,
            },
            type: "profit",
            name: "Прибуток",
        },
// *************************************************
        {
            id: 223,
            styles: {
                bottom: big,
                left: 0,
                width: big,
                height: small,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 224,
            styles: {
                bottom: big + small,
                left: 0,
                width: big,
                height: small,
            },
            type: "buys",
            name: "Великі покупки",
        },
        {
            id: 225,
            styles: {
                bottom: big + small * 2,
                left: 0,
                width: big,
                height: small,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 226,
            styles: {
                bottom: big + small * 3,
                left: 0,
                width: big,
                height: small,
            },
            type: "deputy",
            name: "Депутат",
        },
        {
            id: 227,
            styles: {
                bottom: big + small * 4,
                left: 0,
                width: big,
                height: small,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 228,
            styles: {
                bottom: big + small * 5,
                left: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 229,
            styles: {
                bottom: big + small * 6,
                left: 0,
                width: big,
                height: small,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 230,
            styles: {
                bottom: big + small * 7,
                left: 0,
                width: big,
                height: small,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 231,
            styles: {
                bottom: big + small * 8,
                left: 0,
                width: big,
                height: small,
            },
            type: "buys",
            name: "Великі покупки",
        },
        {
            id: 232,
            styles: {
                bottom: big + small * 9,
                left: 0,
                width: big,
                height: small,
            },
            type: "business",
            name: "Бізнес",
        },
        {
            id: 233,
            styles: {
                bottom: big + small * 10,
                left: 0,
                width: big,
                height: small,
            },
            type: "deputy",
            name: "Депутат",
        },
        {
            id: 234,
            styles: {
                bottom: big + small * 11,
                left: 0,
                width: big,
                height: small,
            },
            type: "target",
            name: "Примхи багатіїв",
        },
        {
            id: 235,
            styles: {
                bottom: big + small * 12,
                left: 0,
                width: big,
                height: small,
            },
            type: "chance",
            name: "Шанс",
        },
        {
            id: 236,
            styles: {
                bottom: big + small * 13,
                left: 0,
                width: big,
                height: small,
            },
            type: "market",
            name: "Ринок",
        },
        {
            id: 237,
            styles: {
                bottom: big + small * 14,
                left: 0,
                width: big,
                height: big,
            },
            type: "profit",
            name: "Прибуток",
        },
// *************************************************
    ];
};
