// Blank
export const TAX = 0.1;
export const APARTMENT_EXPENSES = 200;
export const CAR_EXPENSES = 600;
export const COTTAGE_EXPENSES = 1000;
export const YACHT_EXPENSES = 1500;
export const PLANE_EXPENSES = 5000;
export const MAX_DEBT = 10000;
export const WEDDING_COST = 5000;
export const CHILD_EXPENSES = 300;
export const CHILD_ALLOWANCE = 1000;
export const MAX_HISTORY = 10;
export const RICH_CASH = 3000000;
export const RICH_CASH_FLOW = 50000;

// Rat
export const RAT_OUTER_CIRCLE_FACTOR = 0.693333333;
export const RAT_INNER_CIRCLE_FACTOR = 0.636363636;
export const FIELDS_COUNT_BY_WIDTH_IN_OUTER_CIRCLE = 25;
export const FIELDS_COUNT_BY_WIDTH_IN_INNER_CIRCLE = 26.4;
export const FIELDS_COUNT_BY_HEIGHT_IN_OUTER_CIRCLE = 17.3333333;
export const FIELDS_COUNT_BY_HEIGHT_IN_INNER_CIRCLE = 16.8;
export const ASPECT_RATIO_FIELD_OUTER_CIRCLE = 0.6;
export const ASPECT_RATIO_FIELD_INNER_CIRCLE = 0.714285714;
export const ASPECT_RATIO_HUGE_FIELD_INNER = 0.625;
export const FIELDS_COUNT_OF_OUTER_CIRCLE = 74;
export const FIELDS_COUNT_OF_INNER_CIRCLE = 78;

// Game
export const POOR_CIRCLE_FACTOR = 0.465;
export const RICH_CIRCLE_FACTOR = 0.526315789;
export const CELLS_COUNT_BY_WIDTH = 19;
export const CELLS_COUNT_BY_HEIGHT = 10;
export const FIELDS_COUNT = 54;
export const FIELDS_GAP = 10;
